### ISSUE TITLE
Add container grouping

### ISSUE THREAD

**Issue by natecox** [natecox/corrator#10]
Group containers together in-config and run them by name.

```toml
[containers.ubuntu]
config = "here"

[containers."app name here"]
config = "here"

[containers.etc]
config = "here"

[groups.my-project-name]
containers = [ "ubuntu", "app name here", "etc" ]
```
 
```
corrator --group my-project-name
```
